import Head from 'next/head'
import Footer from '../components/common/footer/Footer'
import HomePage from '../components/pages/HomePage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Temed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <Footer />


    </div>
  )
}
